"""Mise à jour LoanData avec les 2 nouvelles colonnes

Revision ID: adc807458e2b
Revises: 34801192dfe7
Create Date: 2025-06-18 14:28:21.343106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc807458e2b'
down_revision: Union[str, None] = '34801192dfe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loandatas', sa.Column('nb_enfants', sa.Integer(), nullable=True))
    op.add_column('loandatas', sa.Column('quotient_caf', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loandatas', 'quotient_caf')
    op.drop_column('loandatas', 'nb_enfants')
    # ### end Alembic commands ###
